### PR TITLE
KeyValue storing probably done

### PR DESCRIPTION
**Pull request by GajdosDavid**

### CODE REVIEW

**Review by zargham-ahmad — CHANGES_REQUESTED** [review]
After a brief review of the code below is my feedback.

- We should set the default value of the duress_pin.
- We are only checking the remaining pin tries of the user pin I am not sure if we need to check the remaining tries of the duress pin
- PIN_TRY_LIMIT variable is not used anywhere either we can remove it or instead of hard coding the pin try limit when creating the new owner pin we can use this variable (originally it was created for this but somehow missed)
- in the KeyValueRecord class ALG_SECURE_RANDOM, generateData is used which is deprecated, not sure if it is okay to use or if it can cause any security issue.

**Review by DaudNaveed — CHANGES_REQUESTED** [review]
1- The default value of the duress pin is not numeric (causes issues with verifyPin because the duress pin is checked first)
2- default duress pin variable value is not correct (as it is again updating the user pin)
3 - verify pin condition is not correct (! is missing m_duress_pin.check)

Reply:
1- default value of the normal pin which you programmed is not numeric either according to ASCII table, what issues does it casue?
2- yup, my bad
3 - that was intentional as you probably want to check first whether the entered pin is duress and if it is, you delete everything and proceed, on the other hand if it isn't duress, you wanna check if it's at least normal

**Review by zargham-ahmad — CHANGES_REQUESTED** [review]
verify pin function is checking both user pin and duress pin so if the user enters duress pin the output is wrong pin

**Review by zargham-ahmad — APPROVED** [review]

**Review by DaudNaveed — APPROVED** [review]

**Review by zargham-ahmad — CHANGES_REQUESTED** [review]
the PIN's validated flag resets upon deselection of the applet is missing.
Something like the below function

public void deselect() {
        m_user_pin.reset();
    }

Also in apdu file, in changePin function String apdu the last variable should be pin instead of pin_len otherwise pin value is not sent in the apdu.

I have fixed the changes in the last commit

**Pull request merged**
